window.MOCK_EVENTS = [
  {
    id: "e1",
    type: "nightclub",
    title_ar: "برنامج الليلة - DJ + مطرب",
    title_en: "Tonight Program - DJ + Singer",
    title_ku: "پڕۆگرامی ئەم شەوە - DJ + گۆرانیبێژ",
    venue: "Sky Club",
    city: "Erbil",
    date: "2026-01-15",
    time: "10:00 PM",
    priceFromUSD: 20,
    discountPercent: 5, // إذا 0 => لا تظهر
    img: "assets/placeholder.jpg",
    description_ar: "DJ من 10 إلى 12، ثم مطرب من 12 إلى 2.",
    description_en: "DJ 10–12, then singer 12–2.",
    description_ku: "DJ لە 10 بۆ 12، پاشان گۆرانیبێژ لە 12 بۆ 2.",
  },
  {
    id: "e2",
    type: "concert",
    title_ar: "حفلة فنان مشهور",
    title_en: "Famous Artist Concert",
    title_ku: "کۆنسێرتی هونەرمەندی ناسراو",
    venue: "Divan Erbil",
    city: "Erbil",
    date: "2026-02-01",
    time: "8:30 PM",
    priceFromUSD: 35,
    discountPercent: 0,
    img: "assets/placeholder.jpg",
    description_ar: "حجز التذاكر حسب الفئة.",
    description_en: "Tickets by category.",
    description_ku: "بلیت بە پۆل.",
  },
];
